name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
        LANG: en_US.UTF-8
        LANGUAGE: en_US:en
        LC_ALL: en_US.UTF-8
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      env: 
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install packer
    - name: Validate Generic Box Configurations
      env:
        GOGC: 50
        PACKER_LOG: 1
        GOMAXPROCS: 1
        VERSION: 1.0.0
      run: |
        date +"%nStarting generic box validation at %r on %x%n"
        export PACKER_LOG_PATH=generic-docker.txt ; packer validate generic-docker.json &> /dev/null && printf "File  + $(tput setaf 2)generic-docker.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-docker.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-hyperv.txt ; packer validate generic-hyperv.json &> /dev/null && printf "File  + $(tput setaf 2)generic-hyperv.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-hyperv.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-libvirt.txt ; packer validate generic-libvirt.json &> /dev/null && printf "File  + $(tput setaf 2)generic-libvirt.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-libvirt.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-parallels.txt ; packer validate generic-parallels.json &> /dev/null && printf "File  + $(tput setaf 2)generic-parallels.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-parallels.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-virtualbox.txt ; packer validate generic-virtualbox.json &> /dev/null && printf "File  + $(tput setaf 2)generic-virtualbox.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-virtualbox.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-vmware.txt ; packer validate generic-vmware.json &> /dev/null && printf "File  + $(tput setaf 2)generic-vmware.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-vmware.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-libvirt-x32.txt ; packer validate generic-libvirt-x32.json &> /dev/null && printf "File  + $(tput setaf 2)generic-libvirt-x32.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-libvirt-x32.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=generic-virtualbox-x32.txt ; packer validate generic-virtualbox-x32.json &> /dev/null && printf "File  + $(tput setaf 2)generic-virtualbox-x32.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)generic-virtualbox-x32.json$(tput sgr0)\n" ; exit 1 ; }
        date +"%nFinished generic box validation at %r on %x%n"
    - name: Validate Magma Box Configurations
      env:
        GOGC: 50
        PACKER_LOG: 1
        GOMAXPROCS: 1
        VERSION: 1.0.0
      run: |
        date +"%nStarting magma box validation at %r on %x%n"
        export PACKER_LOG_PATH=magma-docker.txt ; packer validate magma-docker.json &> /dev/null && printf "File  + $(tput setaf 2)magma-docker.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)magma-docker.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=magma-hyperv.txt ; packer validate magma-hyperv.json &> /dev/null && printf "File  + $(tput setaf 2)magma-hyperv.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)magma-hyperv.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=magma-libvirt.txt ; packer validate magma-libvirt.json &> /dev/null && printf "File  + $(tput setaf 2)magma-libvirt.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)magma-libvirt.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=magma-virtualbox.txt ; packer validate magma-virtualbox.json &> /dev/null && printf "File  + $(tput setaf 2)magma-virtualbox.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)magma-virtualbox.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=magma-vmware.txt ; packer validate magma-vmware.json &> /dev/null && printf "File  + $(tput setaf 2)magma-vmware.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)magma-vmware.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=developer-hyperv.txt ; packer validate developer-hyperv.json &> /dev/null && printf "File  + $(tput setaf 2)developer-hyperv.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)developer-hyperv.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=developer-libvirt.txt ; packer validate developer-libvirt.json &> /dev/null && printf "File  + $(tput setaf 2)developer-libvirt.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)developer-libvirt.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=developer-ova.txt ; packer validate developer-ova.json &> /dev/null && printf "File  + $(tput setaf 2)developer-ova.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)developer-ova.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=developer-virtualbox.txt ; packer validate developer-virtualbox.json &> /dev/null && printf "File  + $(tput setaf 2)developer-virtualbox.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)developer-virtualbox.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=developer-vmware.txt ; packer validate developer-vmware.json &> /dev/null && printf "File  + $(tput setaf 2)developer-vmware.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)developer-vmware.json$(tput sgr0)\n" ; exit 1 ; }
        date +"%nFinished magma box validation at %r on %x%n"
    - name: Validate Lineage Box Configurations
      env:
        GOGC: 50
        PACKER_LOG: 1
        GOMAXPROCS: 1
        VERSION: 1.0.0
      run: |
        date +"%nStarting lineage box validation at %r on %x%n"
        export PACKER_LOG_PATH=lineage-hyperv.txt ; packer validate lineage-hyperv.json &> /dev/null && printf "File  + $(tput setaf 2)lineage-hyperv.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)lineage-hyperv.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=lineage-libvirt.txt ; packer validate lineage-libvirt.json &> /dev/null && printf "File  + $(tput setaf 2)lineage-libvirt.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)lineage-libvirt.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=lineage-virtualbox.txt ; packer validate lineage-virtualbox.json &> /dev/null && printf "File  + $(tput setaf 2)lineage-virtualbox.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)lineage-virtualbox.json$(tput sgr0)\n" ; exit 1 ; }
        export PACKER_LOG_PATH=lineage-vmware.txt ; packer validate lineage-vmware.json &> /dev/null && printf "File  + $(tput setaf 2)lineage-vmware.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)lineage-vmware.json$(tput sgr0)\n" ; exit 1 ; }
        date +"%nFinished lineage box validation at %r on %x%n"
    - name: Validate Cache Configuration
      env:
        GOGC: 50
        PACKER_LOG: 1
        GOMAXPROCS: 1
        VERSION: 1.0.0
      run: |
        date +"%nStarting cache box validation at %r on %x%n"
        export PACKER_LOG_PATH=packer-cache.txt ; packer validate packer-cache.json &> /dev/null && printf "File  + $(tput setaf 2)packer-cache.json$(tput sgr0)\n" || { printf "File  - $(tput setaf 1)packer-cache.json$(tput sgr0)\n" ; exit 1 ; }
        date +"%nFinished Cache box validation at %r on %x%n"
